//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp1.MAMigration {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MAMigrationSoap", Namespace="MyAdvantechGlobal")]
    public partial class MAMigration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CATALOG_EditOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncSingleSAPCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback CBOM_EditOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncSingleProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncSingleProductV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncPartNoFromSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncCompanyIdFromSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloKiityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MAMigration() {
            this.Url = global::ConsoleApp1.Properties.Settings.Default.ConsoleApp1_MAMigration_MAMigration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CATALOG_EditCompletedEventHandler CATALOG_EditCompleted;
        
        /// <remarks/>
        public event SyncSingleSAPCustomerCompletedEventHandler SyncSingleSAPCustomerCompleted;
        
        /// <remarks/>
        public event CBOM_EditCompletedEventHandler CBOM_EditCompleted;
        
        /// <remarks/>
        public event SyncSingleProductCompletedEventHandler SyncSingleProductCompleted;
        
        /// <remarks/>
        public event SyncSingleProductV2CompletedEventHandler SyncSingleProductV2Completed;
        
        /// <remarks/>
        public event SyncPartNoFromSAPCompletedEventHandler SyncPartNoFromSAPCompleted;
        
        /// <remarks/>
        public event SyncCompanyIdFromSAPCompletedEventHandler SyncCompanyIdFromSAPCompleted;
        
        /// <remarks/>
        public event HelloKiityCompletedEventHandler HelloKiityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/CATALOG_Edit", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CATALOG_Edit(CBOMActions act, string CataID, string CataName, string GroupName, string CataDesc, string CreatedBy, string ImgName) {
            object[] results = this.Invoke("CATALOG_Edit", new object[] {
                        act,
                        CataID,
                        CataName,
                        GroupName,
                        CataDesc,
                        CreatedBy,
                        ImgName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CATALOG_EditAsync(CBOMActions act, string CataID, string CataName, string GroupName, string CataDesc, string CreatedBy, string ImgName) {
            this.CATALOG_EditAsync(act, CataID, CataName, GroupName, CataDesc, CreatedBy, ImgName, null);
        }
        
        /// <remarks/>
        public void CATALOG_EditAsync(CBOMActions act, string CataID, string CataName, string GroupName, string CataDesc, string CreatedBy, string ImgName, object userState) {
            if ((this.CATALOG_EditOperationCompleted == null)) {
                this.CATALOG_EditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCATALOG_EditOperationCompleted);
            }
            this.InvokeAsync("CATALOG_Edit", new object[] {
                        act,
                        CataID,
                        CataName,
                        GroupName,
                        CataDesc,
                        CreatedBy,
                        ImgName}, this.CATALOG_EditOperationCompleted, userState);
        }
        
        private void OnCATALOG_EditOperationCompleted(object arg) {
            if ((this.CATALOG_EditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CATALOG_EditCompleted(this, new CATALOG_EditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/SyncSingleSAPCustomer", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SyncSingleSAPCustomer(string CompanyId, bool isTest, ref string ErrMsg) {
            object[] results = this.Invoke("SyncSingleSAPCustomer", new object[] {
                        CompanyId,
                        isTest,
                        ErrMsg});
            ErrMsg = ((string)(results[1]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SyncSingleSAPCustomerAsync(string CompanyId, bool isTest, string ErrMsg) {
            this.SyncSingleSAPCustomerAsync(CompanyId, isTest, ErrMsg, null);
        }
        
        /// <remarks/>
        public void SyncSingleSAPCustomerAsync(string CompanyId, bool isTest, string ErrMsg, object userState) {
            if ((this.SyncSingleSAPCustomerOperationCompleted == null)) {
                this.SyncSingleSAPCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncSingleSAPCustomerOperationCompleted);
            }
            this.InvokeAsync("SyncSingleSAPCustomer", new object[] {
                        CompanyId,
                        isTest,
                        ErrMsg}, this.SyncSingleSAPCustomerOperationCompleted, userState);
        }
        
        private void OnSyncSingleSAPCustomerOperationCompleted(object arg) {
            if ((this.SyncSingleSAPCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncSingleSAPCustomerCompleted(this, new SyncSingleSAPCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/CBOM_Edit", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CBOM_Edit(CBOMActions act, string CatId, string CatType, string ParentCatId, string CatDesc, string ExtDesc, string UpdBy, int SeqNo, string ConfigRule, string NotExpandCat, string ShowHide) {
            object[] results = this.Invoke("CBOM_Edit", new object[] {
                        act,
                        CatId,
                        CatType,
                        ParentCatId,
                        CatDesc,
                        ExtDesc,
                        UpdBy,
                        SeqNo,
                        ConfigRule,
                        NotExpandCat,
                        ShowHide});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CBOM_EditAsync(CBOMActions act, string CatId, string CatType, string ParentCatId, string CatDesc, string ExtDesc, string UpdBy, int SeqNo, string ConfigRule, string NotExpandCat, string ShowHide) {
            this.CBOM_EditAsync(act, CatId, CatType, ParentCatId, CatDesc, ExtDesc, UpdBy, SeqNo, ConfigRule, NotExpandCat, ShowHide, null);
        }
        
        /// <remarks/>
        public void CBOM_EditAsync(CBOMActions act, string CatId, string CatType, string ParentCatId, string CatDesc, string ExtDesc, string UpdBy, int SeqNo, string ConfigRule, string NotExpandCat, string ShowHide, object userState) {
            if ((this.CBOM_EditOperationCompleted == null)) {
                this.CBOM_EditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCBOM_EditOperationCompleted);
            }
            this.InvokeAsync("CBOM_Edit", new object[] {
                        act,
                        CatId,
                        CatType,
                        ParentCatId,
                        CatDesc,
                        ExtDesc,
                        UpdBy,
                        SeqNo,
                        ConfigRule,
                        NotExpandCat,
                        ShowHide}, this.CBOM_EditOperationCompleted, userState);
        }
        
        private void OnCBOM_EditOperationCompleted(object arg) {
            if ((this.CBOM_EditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CBOM_EditCompleted(this, new CBOM_EditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/SyncSingleProduct", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DimProductSet SyncSingleProduct(string PN, string OrgPrefix, bool isTest, ref string errMsg) {
            object[] results = this.Invoke("SyncSingleProduct", new object[] {
                        PN,
                        OrgPrefix,
                        isTest,
                        errMsg});
            errMsg = ((string)(results[1]));
            return ((DimProductSet)(results[0]));
        }
        
        /// <remarks/>
        public void SyncSingleProductAsync(string PN, string OrgPrefix, bool isTest, string errMsg) {
            this.SyncSingleProductAsync(PN, OrgPrefix, isTest, errMsg, null);
        }
        
        /// <remarks/>
        public void SyncSingleProductAsync(string PN, string OrgPrefix, bool isTest, string errMsg, object userState) {
            if ((this.SyncSingleProductOperationCompleted == null)) {
                this.SyncSingleProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncSingleProductOperationCompleted);
            }
            this.InvokeAsync("SyncSingleProduct", new object[] {
                        PN,
                        OrgPrefix,
                        isTest,
                        errMsg}, this.SyncSingleProductOperationCompleted, userState);
        }
        
        private void OnSyncSingleProductOperationCompleted(object arg) {
            if ((this.SyncSingleProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncSingleProductCompleted(this, new SyncSingleProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/SyncSingleProductV2", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DimProductSet SyncSingleProductV2(string PN, string OrgPrefix, bool isTest, ref string errMsg, bool isSyncPIS) {
            object[] results = this.Invoke("SyncSingleProductV2", new object[] {
                        PN,
                        OrgPrefix,
                        isTest,
                        errMsg,
                        isSyncPIS});
            errMsg = ((string)(results[1]));
            return ((DimProductSet)(results[0]));
        }
        
        /// <remarks/>
        public void SyncSingleProductV2Async(string PN, string OrgPrefix, bool isTest, string errMsg, bool isSyncPIS) {
            this.SyncSingleProductV2Async(PN, OrgPrefix, isTest, errMsg, isSyncPIS, null);
        }
        
        /// <remarks/>
        public void SyncSingleProductV2Async(string PN, string OrgPrefix, bool isTest, string errMsg, bool isSyncPIS, object userState) {
            if ((this.SyncSingleProductV2OperationCompleted == null)) {
                this.SyncSingleProductV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncSingleProductV2OperationCompleted);
            }
            this.InvokeAsync("SyncSingleProductV2", new object[] {
                        PN,
                        OrgPrefix,
                        isTest,
                        errMsg,
                        isSyncPIS}, this.SyncSingleProductV2OperationCompleted, userState);
        }
        
        private void OnSyncSingleProductV2OperationCompleted(object arg) {
            if ((this.SyncSingleProductV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncSingleProductV2Completed(this, new SyncSingleProductV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/SyncPartNoFromSAP", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SyncPartNoFromSAP(string pn) {
            object[] results = this.Invoke("SyncPartNoFromSAP", new object[] {
                        pn});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SyncPartNoFromSAPAsync(string pn) {
            this.SyncPartNoFromSAPAsync(pn, null);
        }
        
        /// <remarks/>
        public void SyncPartNoFromSAPAsync(string pn, object userState) {
            if ((this.SyncPartNoFromSAPOperationCompleted == null)) {
                this.SyncPartNoFromSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncPartNoFromSAPOperationCompleted);
            }
            this.InvokeAsync("SyncPartNoFromSAP", new object[] {
                        pn}, this.SyncPartNoFromSAPOperationCompleted, userState);
        }
        
        private void OnSyncPartNoFromSAPOperationCompleted(object arg) {
            if ((this.SyncPartNoFromSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncPartNoFromSAPCompleted(this, new SyncPartNoFromSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/SyncCompanyIdFromSAP", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SyncCompanyIdFromSAP(string companyid) {
            object[] results = this.Invoke("SyncCompanyIdFromSAP", new object[] {
                        companyid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SyncCompanyIdFromSAPAsync(string companyid) {
            this.SyncCompanyIdFromSAPAsync(companyid, null);
        }
        
        /// <remarks/>
        public void SyncCompanyIdFromSAPAsync(string companyid, object userState) {
            if ((this.SyncCompanyIdFromSAPOperationCompleted == null)) {
                this.SyncCompanyIdFromSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncCompanyIdFromSAPOperationCompleted);
            }
            this.InvokeAsync("SyncCompanyIdFromSAP", new object[] {
                        companyid}, this.SyncCompanyIdFromSAPOperationCompleted, userState);
        }
        
        private void OnSyncCompanyIdFromSAPOperationCompleted(object arg) {
            if ((this.SyncCompanyIdFromSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncCompanyIdFromSAPCompleted(this, new SyncCompanyIdFromSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("MyAdvantechGlobal/HelloKiity", RequestNamespace="MyAdvantechGlobal", ResponseNamespace="MyAdvantechGlobal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloKiity() {
            object[] results = this.Invoke("HelloKiity", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloKiityAsync() {
            this.HelloKiityAsync(null);
        }
        
        /// <remarks/>
        public void HelloKiityAsync(object userState) {
            if ((this.HelloKiityOperationCompleted == null)) {
                this.HelloKiityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloKiityOperationCompleted);
            }
            this.InvokeAsync("HelloKiity", new object[0], this.HelloKiityOperationCompleted, userState);
        }
        
        private void OnHelloKiityOperationCompleted(object arg) {
            if ((this.HelloKiityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloKiityCompleted(this, new HelloKiityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public enum CBOMActions {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        UPDATE,
        
        /// <remarks/>
        DELETE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public partial class DimProductSet {
        
        private SAP_PRODUCT[] productField;
        
        private SAP_PRODUCT_ORG[] product_OrgField;
        
        private SAP_PRODUCT_STATUS[] product_StatusField;
        
        private SAP_PRODUCT_ABC[] product_ABCField;
        
        private SAP_PRODUCT_STATUS_ORDERABLE[] product_OrderableField;
        
        /// <remarks/>
        public SAP_PRODUCT[] Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public SAP_PRODUCT_ORG[] Product_Org {
            get {
                return this.product_OrgField;
            }
            set {
                this.product_OrgField = value;
            }
        }
        
        /// <remarks/>
        public SAP_PRODUCT_STATUS[] Product_Status {
            get {
                return this.product_StatusField;
            }
            set {
                this.product_StatusField = value;
            }
        }
        
        /// <remarks/>
        public SAP_PRODUCT_ABC[] Product_ABC {
            get {
                return this.product_ABCField;
            }
            set {
                this.product_ABCField = value;
            }
        }
        
        /// <remarks/>
        public SAP_PRODUCT_STATUS_ORDERABLE[] Product_Orderable {
            get {
                return this.product_OrderableField;
            }
            set {
                this.product_OrderableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public partial class SAP_PRODUCT {
        
        private string pART_NOField;
        
        private string mODEL_NOField;
        
        private string mATERIAL_GROUPField;
        
        private string dIVISIONField;
        
        private string pRODUCT_HIERARCHYField;
        
        private string pRODUCT_GROUPField;
        
        private string pRODUCT_DIVISIONField;
        
        private string pRODUCT_LINEField;
        
        private string gENITEMCATGRPField;
        
        private string pRODUCT_DESCField;
        
        private string rOHS_FLAGField;
        
        private string sTATUSField;
        
        private string eGROUPField;
        
        private string eDIVISIONField;
        
        private System.Nullable<double> nET_WEIGHTField;
        
        private System.Nullable<double> gROSS_WEIGHTField;
        
        private string wEIGHT_UNITField;
        
        private System.Nullable<double> vOLUMEField;
        
        private string vOLUME_UNITField;
        
        private string cREATE_DATEField;
        
        private string lAST_UPD_DATEField;
        
        private string pRODUCT_TYPEField;
        
        private string gIP_CODEField;
        
        private string sIZE_DIMENSIONSField;
        
        private string sOURCE_LOCATIONField;
        
        private string pRODUCT_FAMILYField;
        
        private string pLM_STATUSField;
        
        /// <remarks/>
        public string PART_NO {
            get {
                return this.pART_NOField;
            }
            set {
                this.pART_NOField = value;
            }
        }
        
        /// <remarks/>
        public string MODEL_NO {
            get {
                return this.mODEL_NOField;
            }
            set {
                this.mODEL_NOField = value;
            }
        }
        
        /// <remarks/>
        public string MATERIAL_GROUP {
            get {
                return this.mATERIAL_GROUPField;
            }
            set {
                this.mATERIAL_GROUPField = value;
            }
        }
        
        /// <remarks/>
        public string DIVISION {
            get {
                return this.dIVISIONField;
            }
            set {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_HIERARCHY {
            get {
                return this.pRODUCT_HIERARCHYField;
            }
            set {
                this.pRODUCT_HIERARCHYField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_GROUP {
            get {
                return this.pRODUCT_GROUPField;
            }
            set {
                this.pRODUCT_GROUPField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_DIVISION {
            get {
                return this.pRODUCT_DIVISIONField;
            }
            set {
                this.pRODUCT_DIVISIONField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_LINE {
            get {
                return this.pRODUCT_LINEField;
            }
            set {
                this.pRODUCT_LINEField = value;
            }
        }
        
        /// <remarks/>
        public string GENITEMCATGRP {
            get {
                return this.gENITEMCATGRPField;
            }
            set {
                this.gENITEMCATGRPField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_DESC {
            get {
                return this.pRODUCT_DESCField;
            }
            set {
                this.pRODUCT_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string ROHS_FLAG {
            get {
                return this.rOHS_FLAGField;
            }
            set {
                this.rOHS_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string EGROUP {
            get {
                return this.eGROUPField;
            }
            set {
                this.eGROUPField = value;
            }
        }
        
        /// <remarks/>
        public string EDIVISION {
            get {
                return this.eDIVISIONField;
            }
            set {
                this.eDIVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> NET_WEIGHT {
            get {
                return this.nET_WEIGHTField;
            }
            set {
                this.nET_WEIGHTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> GROSS_WEIGHT {
            get {
                return this.gROSS_WEIGHTField;
            }
            set {
                this.gROSS_WEIGHTField = value;
            }
        }
        
        /// <remarks/>
        public string WEIGHT_UNIT {
            get {
                return this.wEIGHT_UNITField;
            }
            set {
                this.wEIGHT_UNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> VOLUME {
            get {
                return this.vOLUMEField;
            }
            set {
                this.vOLUMEField = value;
            }
        }
        
        /// <remarks/>
        public string VOLUME_UNIT {
            get {
                return this.vOLUME_UNITField;
            }
            set {
                this.vOLUME_UNITField = value;
            }
        }
        
        /// <remarks/>
        public string CREATE_DATE {
            get {
                return this.cREATE_DATEField;
            }
            set {
                this.cREATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string LAST_UPD_DATE {
            get {
                return this.lAST_UPD_DATEField;
            }
            set {
                this.lAST_UPD_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_TYPE {
            get {
                return this.pRODUCT_TYPEField;
            }
            set {
                this.pRODUCT_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string GIP_CODE {
            get {
                return this.gIP_CODEField;
            }
            set {
                this.gIP_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string SIZE_DIMENSIONS {
            get {
                return this.sIZE_DIMENSIONSField;
            }
            set {
                this.sIZE_DIMENSIONSField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_LOCATION {
            get {
                return this.sOURCE_LOCATIONField;
            }
            set {
                this.sOURCE_LOCATIONField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_FAMILY {
            get {
                return this.pRODUCT_FAMILYField;
            }
            set {
                this.pRODUCT_FAMILYField = value;
            }
        }
        
        /// <remarks/>
        public string PLM_STATUS {
            get {
                return this.pLM_STATUSField;
            }
            set {
                this.pLM_STATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public partial class SAP_PRODUCT_STATUS_ORDERABLE {
        
        private string pART_NOField;
        
        private string sALES_ORGField;
        
        private string dIST_CHANNELField;
        
        private string pRODUCT_STATUSField;
        
        private System.Nullable<decimal> mIN_ORDER_QTYField;
        
        private System.Nullable<decimal> mIN_DLV_QTYField;
        
        private System.Nullable<decimal> mIN_BTO_QTYField;
        
        private string dLV_PLANTField;
        
        private string mATERIAL_PRICING_GRPField;
        
        private string vALID_DATEField;
        
        private string iTEM_CATEGORY_GROUPField;
        
        private int idField;
        
        /// <remarks/>
        public string PART_NO {
            get {
                return this.pART_NOField;
            }
            set {
                this.pART_NOField = value;
            }
        }
        
        /// <remarks/>
        public string SALES_ORG {
            get {
                return this.sALES_ORGField;
            }
            set {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        public string DIST_CHANNEL {
            get {
                return this.dIST_CHANNELField;
            }
            set {
                this.dIST_CHANNELField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_STATUS {
            get {
                return this.pRODUCT_STATUSField;
            }
            set {
                this.pRODUCT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_ORDER_QTY {
            get {
                return this.mIN_ORDER_QTYField;
            }
            set {
                this.mIN_ORDER_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_DLV_QTY {
            get {
                return this.mIN_DLV_QTYField;
            }
            set {
                this.mIN_DLV_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_BTO_QTY {
            get {
                return this.mIN_BTO_QTYField;
            }
            set {
                this.mIN_BTO_QTYField = value;
            }
        }
        
        /// <remarks/>
        public string DLV_PLANT {
            get {
                return this.dLV_PLANTField;
            }
            set {
                this.dLV_PLANTField = value;
            }
        }
        
        /// <remarks/>
        public string MATERIAL_PRICING_GRP {
            get {
                return this.mATERIAL_PRICING_GRPField;
            }
            set {
                this.mATERIAL_PRICING_GRPField = value;
            }
        }
        
        /// <remarks/>
        public string VALID_DATE {
            get {
                return this.vALID_DATEField;
            }
            set {
                this.vALID_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string ITEM_CATEGORY_GROUP {
            get {
                return this.iTEM_CATEGORY_GROUPField;
            }
            set {
                this.iTEM_CATEGORY_GROUPField = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public partial class SAP_PRODUCT_ABC {
        
        private string pART_NOField;
        
        private string pLANTField;
        
        private string aBC_INDICATORField;
        
        private System.Nullable<int> pLANNED_DEL_TIMEField;
        
        private System.Nullable<int> gP_PROCESSING_TIMEField;
        
        private System.Nullable<int> iN_HOUSE_PRODUCTIONField;
        
        private string profitCenterField;
        
        private string ctrl_CodeField;
        
        private System.Nullable<double> safety_stockField;
        
        private System.Nullable<double> min_safety_stockField;
        
        private System.Nullable<decimal> service_levelField;
        
        private System.Nullable<decimal> mIN_LOT_SIZEField;
        
        private long idField;
        
        private string fREIGHT_METHODField;
        
        private string cOUNTRY_ORIGINField;
        
        /// <remarks/>
        public string PART_NO {
            get {
                return this.pART_NOField;
            }
            set {
                this.pART_NOField = value;
            }
        }
        
        /// <remarks/>
        public string PLANT {
            get {
                return this.pLANTField;
            }
            set {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        public string ABC_INDICATOR {
            get {
                return this.aBC_INDICATORField;
            }
            set {
                this.aBC_INDICATORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PLANNED_DEL_TIME {
            get {
                return this.pLANNED_DEL_TIMEField;
            }
            set {
                this.pLANNED_DEL_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GP_PROCESSING_TIME {
            get {
                return this.gP_PROCESSING_TIMEField;
            }
            set {
                this.gP_PROCESSING_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IN_HOUSE_PRODUCTION {
            get {
                return this.iN_HOUSE_PRODUCTIONField;
            }
            set {
                this.iN_HOUSE_PRODUCTIONField = value;
            }
        }
        
        /// <remarks/>
        public string ProfitCenter {
            get {
                return this.profitCenterField;
            }
            set {
                this.profitCenterField = value;
            }
        }
        
        /// <remarks/>
        public string Ctrl_Code {
            get {
                return this.ctrl_CodeField;
            }
            set {
                this.ctrl_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> safety_stock {
            get {
                return this.safety_stockField;
            }
            set {
                this.safety_stockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> min_safety_stock {
            get {
                return this.min_safety_stockField;
            }
            set {
                this.min_safety_stockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> service_level {
            get {
                return this.service_levelField;
            }
            set {
                this.service_levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_LOT_SIZE {
            get {
                return this.mIN_LOT_SIZEField;
            }
            set {
                this.mIN_LOT_SIZEField = value;
            }
        }
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string FREIGHT_METHOD {
            get {
                return this.fREIGHT_METHODField;
            }
            set {
                this.fREIGHT_METHODField = value;
            }
        }
        
        /// <remarks/>
        public string COUNTRY_ORIGIN {
            get {
                return this.cOUNTRY_ORIGINField;
            }
            set {
                this.cOUNTRY_ORIGINField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public partial class SAP_PRODUCT_STATUS {
        
        private string pART_NOField;
        
        private string sALES_ORGField;
        
        private string dIST_CHANNELField;
        
        private string pRODUCT_STATUSField;
        
        private System.Nullable<decimal> mIN_ORDER_QTYField;
        
        private System.Nullable<decimal> mIN_DLV_QTYField;
        
        private System.Nullable<decimal> mIN_BTO_QTYField;
        
        private string dLV_PLANTField;
        
        private string mATERIAL_PRICING_GRPField;
        
        private string vALID_DATEField;
        
        private string iTEM_CATEGORY_GROUPField;
        
        private long idField;
        
        /// <remarks/>
        public string PART_NO {
            get {
                return this.pART_NOField;
            }
            set {
                this.pART_NOField = value;
            }
        }
        
        /// <remarks/>
        public string SALES_ORG {
            get {
                return this.sALES_ORGField;
            }
            set {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        public string DIST_CHANNEL {
            get {
                return this.dIST_CHANNELField;
            }
            set {
                this.dIST_CHANNELField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUCT_STATUS {
            get {
                return this.pRODUCT_STATUSField;
            }
            set {
                this.pRODUCT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_ORDER_QTY {
            get {
                return this.mIN_ORDER_QTYField;
            }
            set {
                this.mIN_ORDER_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_DLV_QTY {
            get {
                return this.mIN_DLV_QTYField;
            }
            set {
                this.mIN_DLV_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MIN_BTO_QTY {
            get {
                return this.mIN_BTO_QTYField;
            }
            set {
                this.mIN_BTO_QTYField = value;
            }
        }
        
        /// <remarks/>
        public string DLV_PLANT {
            get {
                return this.dLV_PLANTField;
            }
            set {
                this.dLV_PLANTField = value;
            }
        }
        
        /// <remarks/>
        public string MATERIAL_PRICING_GRP {
            get {
                return this.mATERIAL_PRICING_GRPField;
            }
            set {
                this.mATERIAL_PRICING_GRPField = value;
            }
        }
        
        /// <remarks/>
        public string VALID_DATE {
            get {
                return this.vALID_DATEField;
            }
            set {
                this.vALID_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string ITEM_CATEGORY_GROUP {
            get {
                return this.iTEM_CATEGORY_GROUPField;
            }
            set {
                this.iTEM_CATEGORY_GROUPField = value;
            }
        }
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="MyAdvantechGlobal")]
    public partial class SAP_PRODUCT_ORG {
        
        private string pART_NOField;
        
        private string oRG_IDField;
        
        private string dIST_CHANNELField;
        
        private string sTATUSField;
        
        private string b2BONLINEField;
        
        private string dELIVERYPLANTField;
        
        private string pRICINGGROUPField;
        
        private string lAST_UPD_DATEField;
        
        private System.Nullable<int> mIN_ORD_QTYField;
        
        private System.Nullable<int> mIN_DLV_QTYField;
        
        private long idField;
        
        /// <remarks/>
        public string PART_NO {
            get {
                return this.pART_NOField;
            }
            set {
                this.pART_NOField = value;
            }
        }
        
        /// <remarks/>
        public string ORG_ID {
            get {
                return this.oRG_IDField;
            }
            set {
                this.oRG_IDField = value;
            }
        }
        
        /// <remarks/>
        public string DIST_CHANNEL {
            get {
                return this.dIST_CHANNELField;
            }
            set {
                this.dIST_CHANNELField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string B2BONLINE {
            get {
                return this.b2BONLINEField;
            }
            set {
                this.b2BONLINEField = value;
            }
        }
        
        /// <remarks/>
        public string DELIVERYPLANT {
            get {
                return this.dELIVERYPLANTField;
            }
            set {
                this.dELIVERYPLANTField = value;
            }
        }
        
        /// <remarks/>
        public string PRICINGGROUP {
            get {
                return this.pRICINGGROUPField;
            }
            set {
                this.pRICINGGROUPField = value;
            }
        }
        
        /// <remarks/>
        public string LAST_UPD_DATE {
            get {
                return this.lAST_UPD_DATEField;
            }
            set {
                this.lAST_UPD_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MIN_ORD_QTY {
            get {
                return this.mIN_ORD_QTYField;
            }
            set {
                this.mIN_ORD_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MIN_DLV_QTY {
            get {
                return this.mIN_DLV_QTYField;
            }
            set {
                this.mIN_DLV_QTYField = value;
            }
        }
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CATALOG_EditCompletedEventHandler(object sender, CATALOG_EditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CATALOG_EditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CATALOG_EditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SyncSingleSAPCustomerCompletedEventHandler(object sender, SyncSingleSAPCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncSingleSAPCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncSingleSAPCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CBOM_EditCompletedEventHandler(object sender, CBOM_EditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CBOM_EditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CBOM_EditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SyncSingleProductCompletedEventHandler(object sender, SyncSingleProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncSingleProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncSingleProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DimProductSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DimProductSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SyncSingleProductV2CompletedEventHandler(object sender, SyncSingleProductV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncSingleProductV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncSingleProductV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DimProductSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DimProductSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SyncPartNoFromSAPCompletedEventHandler(object sender, SyncPartNoFromSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncPartNoFromSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncPartNoFromSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SyncCompanyIdFromSAPCompletedEventHandler(object sender, SyncCompanyIdFromSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncCompanyIdFromSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncCompanyIdFromSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void HelloKiityCompletedEventHandler(object sender, HelloKiityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloKiityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloKiityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591